Repository ohmtech-rdi/eurorack-blocks, pull requests merged in 2022-01, with the labels that each got.

#239 Erbb gyp refactor
  blocks/test/test.gyp
  build-system/erbb/__init__.py
  build-system/erbui/generators/vcvrack/code.py
  build-system/erbui/generators/vcvrack/code_template.cpp
  eurorack-blocks.gypi
  include/erb/Led.hpp
  include/erb/def.h
  include/erb/detail/Animation.hpp
  include/erb/erb-daisy.gypi
  include/erb/erb-vcvrack.gypi
  include/erb/erb.gypi
  include/erb/vcvrack/BoardGeneric.hpp
  include/erb/vcvrack/VcvWidgets.h
  samples/bypass/build.py
  samples/bypass/bypass-src.gypi
  samples/bypass/bypass.gyp
  samples/drop/build.py
  samples/drop/drop-src.gypi
  samples/drop/drop.gyp
  samples/dsp/Filter2Poles.cpp
  samples/dsp/dsp.gypi
  samples/reverb/build.py
  samples/reverb/reverb-src.gypi
  samples/reverb/reverb.gyp
  test/data/build.py
  test/data/kivu12-src.gypi
  test/data/kivu12.gyp
  test/field/build.py
  test/field/field-src.gypi
  test/field/field.gyp
  test/kivu12_adc/build.py
  test/kivu12_adc/kivu12-src.gypi
  test/kivu12_adc/kivu12.gyp
  test/kivu12_gi/build.py
  test/kivu12_gi/kivu12-src.gypi
  test/kivu12_gi/kivu12.gyp
  test/kivu12_go/build.py
  test/kivu12_go/kivu12-src.gypi
  test/kivu12_go/kivu12.gyp
  test/micropatch/build.py
  test/micropatch/micropatch-src.gypi
  test/micropatch/micropatch.gyp
  test/vcvrack/vcvrack.gyp
Labels: enhancement

#240 Erbb lang
  build-system/build-system.gyp
  build-system/erbb/adapter.py
  build-system/erbb/analyser.py
  build-system/erbb/arpeggio/__init__.py
  build-system/erbb/ast.py
  build-system/erbb/error.py
  build-system/erbb/grammar.py
  build-system/erbb/parser.py
  build-system/erbb/tests/__init__.py
  build-system/erbb/tests/mock.py
  build-system/erbb/tests/test_parser.py
  build-system/erbb/visitor.py
Labels: feature

#242 Erbb vcvrack gyp generator
  .gitignore
  blocks/test/configure.py
  build-system/build-system.gyp
  build-system/erbb/__init__.py
  build-system/erbb/generators/__init__.py
  build-system/erbb/generators/vcvrack/__init__.py
  build-system/erbb/generators/vcvrack/project.py
  build-system/erbb/generators/vcvrack/project_template.gyp
  samples/bypass/Bypass.erbb
  samples/bypass/build.py
  samples/bypass/configure.py
  samples/drop/Drop.erbb
  samples/drop/build.py
  samples/drop/configure.py
  samples/dsp/dsp.erbb
  samples/reverb/Reverb.erbb
  samples/reverb/build.py
  samples/reverb/configure.py
  test/data/Kivu12.erbb
  test/data/build.py
  test/data/configure.py
  test/field/Field.erbb
  test/field/build.py
  test/field/configure.py
  test/kivu12_adc/Kivu12.erbb
  test/kivu12_adc/build.py
  test/kivu12_adc/configure.py
  test/kivu12_gi/Kivu12.erbb
  test/kivu12_gi/build.py
  test/kivu12_gi/configure.py
  test/kivu12_go/Kivu12.erbb
  test/kivu12_go/build.py
  test/kivu12_go/configure.py
  test/micropatch/Micropatch.erbb
  test/micropatch/build.py
  test/micropatch/configure.py
  test/vcvrack/VcvRack.erbb
  test/vcvrack/build.py
  test/vcvrack/configure.py
Labels: feature

#243 Erbb daisy gyp generator
  .gitignore
  build-system/build-system.gyp
  build-system/erbb/__init__.py
  build-system/erbb/generators/daisy/__init__.py
  build-system/erbb/generators/daisy/project.py
  build-system/erbb/generators/daisy/project_template.gyp
  samples/bypass/build.py
  samples/drop/build.py
  samples/reverb/build.py
  test/data/build.py
  test/field/build.py
  test/kivu12_adc/build.py
  test/kivu12_gi/build.py
  test/kivu12_go/build.py
  test/micropatch/build.py
Labels: feature

#244 Erbb vscode generator
  build-system/build-system.gyp
  build-system/erbb/__init__.py
  build-system/erbb/generators/vscode/__init__.py
  build-system/erbb/generators/vscode/launch.py
  build-system/erbb/generators/vscode/launch_template.json
  build-system/erbb/generators/vscode/svd/STM32H750x.svd
  build-system/erbb/generators/vscode/tasks.py
  build-system/erbb/generators/vscode/tasks_template.json
  samples/bypass/configure.py
  samples/drop/configure.py
  samples/reverb/configure.py
  test/data/configure.py
  test/field/configure.py
  test/kivu12_adc/configure.py
  test/kivu12_gi/configure.py
  test/kivu12_go/configure.py
  test/micropatch/configure.py
  test/vcvrack/configure.py
Labels: feature

#245 Erbb cli
  .github/workflows/macos_10_15.yml
  .github/workflows/ubuntu_20_04.yml
  build-system/build-system.gyp
  build-system/init.sh
  build-system/scripts/erbb
  samples/bypass/Bypass.erbui
  samples/bypass/Bypass.h
Labels: feature

#246 Remove unused scripts and gyp files
  samples/bypass/build.py
  samples/bypass/bypass-src.gypi
  samples/bypass/bypass.gyp
  samples/bypass/configure.py
  samples/bypass/deploy.py
  samples/drop/build.py
  samples/drop/configure.py
  samples/drop/deploy.py
  samples/drop/drop-src.gypi
  samples/drop/drop.gyp
  samples/dsp/dsp.gypi
  samples/reverb/build.py
  samples/reverb/configure.py
  samples/reverb/deploy.py
  samples/reverb/reverb-src.gypi
  samples/reverb/reverb.gyp
  test/data/build.py
  test/data/configure.py
  test/data/deploy.py
  test/data/kivu12-src.gypi
  test/data/kivu12.gyp
  test/field/build.py
  test/field/configure.py
  test/field/deploy.py
  test/field/field-src.gypi
  test/field/field.gyp
  test/kivu12_adc/build.py
  test/kivu12_adc/configure.py
  test/kivu12_adc/deploy.py
  test/kivu12_adc/kivu12-src.gypi
  test/kivu12_adc/kivu12.gyp
  test/kivu12_gi/build.py
  test/kivu12_gi/configure.py
  test/kivu12_gi/deploy.py
  test/kivu12_gi/kivu12-src.gypi
  test/kivu12_gi/kivu12.gyp
  test/kivu12_go/build.py
  test/kivu12_go/configure.py
  test/kivu12_go/deploy.py
  test/kivu12_go/kivu12-src.gypi
  test/kivu12_go/kivu12.gyp
  test/micropatch/build.py
  test/micropatch/configure.py
  test/micropatch/deploy.py
  test/micropatch/micropatch-src.gypi
  test/micropatch/micropatch.gyp
  test/vcvrack/vcvrack.gyp
Labels: enhancement

#248 Erbb lang documentation
  README.md
  documentation/README.md
  documentation/documentation.gyp
  documentation/erbb/grammar.md
  documentation/erbb/lexical.md
  documentation/erbui/grammar.md
  documentation/erbui/lexical.md
  samples/bypass/README.md
  samples/drop/README.md
  samples/drop/video-thumbnail.png
  samples/reverb/README.md
  samples/reverb/Reverb.erbb
  samples/reverb/photo.png
Labels: documentation

#249 Add erbb xcode syntax highlighter to install script
  build-system/xcode/README.md
  build-system/xcode/install.py
Labels: feature

#250 Erbb init
  build-system/build-system.gyp
  build-system/erbb/__init__.py
  build-system/erbb/generators/init/__init__.py
  build-system/erbb/generators/init/project.py
  build-system/erbb/generators/init/project_template.cpp
  build-system/erbb/generators/init/project_template.erbb
  build-system/erbb/generators/init/project_template.erbui
  build-system/erbb/generators/init/project_template.h
  build-system/scripts/erbb
Labels: feature

#254 Add erbb init to github actions workflows
  .github/workflows/macos_10_15.yml
  .github/workflows/ubuntu_20_04.yml
Labels: feature

#256 Add data and ui headers to vcvrack project generator
  build-system/erbb/generators/vcvrack/project.py
Labels: enhancement

#257 Erbb data
  build-system/build-system.gyp
  build-system/erbb/__init__.py
  build-system/erbb/analyser.py
  build-system/erbb/ast.py
  build-system/erbb/generators/data/code.py
  build-system/erbb/generators/data/code_template.cpp
  build-system/erbb/generators/data/code_template.h
  build-system/erbb/generators/init/project_template.erbb
  build-system/erbb/grammar.py
  build-system/erbb/visitor.py
  build-system/erbui/__init__.py
  build-system/erbui/analyser.py
  build-system/erbui/ast.py
  build-system/erbui/grammar.py
  build-system/erbui/visitor.py
  build-system/xcode/Erbb.xclangspec
  documentation/erbb/grammar.md
  documentation/erbui/grammar.md
  test/data/Kivu12.cpp
  test/data/Kivu12.erbb
  test/data/Kivu12.erbui
  test/data/Kivu12.h
Labels: enhancement

#259 Fix xcode13 override errors
  include/erb/def.h
  include/erb/vcvrack/BoardDaisyField.h
  include/erb/vcvrack/BoardDaisyMicropatch.h
  include/erb/vcvrack/BoardDaisySeed.h
  include/erb/vcvrack/BoardKivu12.h
  include/erb/vcvrack/VcvWidgets.h
Labels: bug

#262 Pin kicad to 5.1.12
  .github/workflows/macos_10_15.yml
Labels: bug

#261 Build system pip requirements
  .github/workflows/macos_10_15.yml
  .github/workflows/ubuntu_20_04.yml
  requirements.txt
  requirements/build-system.txt
Labels: enhancement

#263 Build system install script
  .github/workflows/macos_10_15.yml
  .github/workflows/ubuntu_20_04.yml
  build-system/install.py
Labels: enhancement

#264 Erbb setup
  .github/workflows/macos_10_15.yml
  .github/workflows/ubuntu_20_04.yml
  build-system/scripts/erbb
Labels: enhancement

#272 Qspi support
  build-system/erbb/__init__.py
  build-system/erbb/analyser.py
  build-system/erbb/ast.py
  build-system/erbb/generators/daisy/project.py
  build-system/erbb/generators/daisy/project_template.gyp
  build-system/erbb/grammar.py
  build-system/erbb/visitor.py
  build-system/erbui/generators/daisy/code_template.cpp
  build-system/scripts/erbb
  build-system/xcode/Erbb.xclangspec
  include/erb/daisy.gypi
Labels: feature

#273 Sample kick
  README.md
  samples/dsp/Ramp.h
  samples/dsp/Ramp.hpp
  samples/dsp/dsp.erbb
  samples/kick/ClockEstimator.cpp
  samples/kick/ClockEstimator.h
  samples/kick/Kick.cpp
  samples/kick/Kick.erbb
  samples/kick/Kick.erbui
  samples/kick/Kick.h
  samples/kick/Presence.cpp
  samples/kick/Presence.h
  samples/kick/README.md
  samples/kick/Space.cpp
  samples/kick/Space.h
  samples/kick/VoiceBody.cpp
  samples/kick/VoiceBody.h
  samples/kick/VoiceBody.hpp
  samples/kick/VoiceTransient.cpp
  samples/kick/VoiceTransient.h
  samples/kick/VoiceTransient.hpp
  samples/kick/VoicesBody.cpp
  samples/kick/VoicesBody.h
  samples/kick/VoicesBody.hpp
  samples/kick/VoicesTransient.cpp
  samples/kick/VoicesTransient.h
  samples/kick/media/body.wav
  samples/kick/media/transient01.wav
  samples/kick/media/transient02.wav
  samples/kick/media/transient03.wav
  samples/kick/media/transient04.wav
  samples/kick/media/transient05.wav
  samples/kick/media/transient06.wav
  samples/kick/media/transient07.wav
  samples/kick/media/transient08.wav
  samples/kick/media/transient09.wav
  samples/kick/media/transient10.wav
  samples/kick/media/transient11.wav
  samples/kick/media/transient12.wav
  samples/kick/media/transient13.wav
  samples/kick/media/transient14.wav
  samples/kick/media/transient15.wav
  samples/kick/media/transient16.wav
  samples/kick/media/transient17.wav
  samples/kick/media/transient18.wav
  samples/kick/screenshot.png
Labels: feature

#274 Add ci check for kick sample
  .github/workflows/macos_10_15.yml
  .github/workflows/ubuntu_20_04.yml
Labels: enhancement

#275 Sample stream modes
  build-system/erbb/analyser.py
  build-system/erbb/ast.py
  build-system/erbb/generators/data/code.py
  build-system/erbb/grammar.py
  build-system/erbb/visitor.py
  build-system/xcode/Erbb.xclangspec
  documentation/erbb/grammar.md
  include/erb/AudioSample.h
  samples/kick/VoiceBody.hpp
  samples/kick/VoiceTransient.hpp
  samples/kick/VoicesTransient.cpp
  samples/kick/VoicesTransient.h
  test/data/Kivu12.cpp
  test/data/Kivu12.erbb
Labels: enhancement

#276 Doc rtd
  .gitignore
  .readthedocs.yml
  README.md
  documentation/Makefile
  documentation/README.md
  documentation/_static/css/custom.css
  documentation/conf.py
  documentation/controls/README.md
  documentation/documentation.gyp
  documentation/erbb/grammar.md
  documentation/erbb/lexical.md
  documentation/erbui/grammar.md
  documentation/erbui/lexical.md
  documentation/getting-started/before.md
  documentation/getting-started/first-add-filter.png
  documentation/getting-started/first-add-freq.png
  documentation/getting-started/first.md
  documentation/getting-started/setup-configure.png
  documentation/getting-started/setup-debug-document.png
  documentation/getting-started/setup-debug-executable.png
  documentation/getting-started/setup-debug-scheme.png
  documentation/getting-started/setup-rack-audio.png
  documentation/getting-started/setup-rack.png
  documentation/getting-started/setup-xcode.png
  documentation/getting-started/setup.md
  documentation/getting-started/what-boards.png
  documentation/getting-started/what.md
  documentation/guides/drop-label-positioning.png
  documentation/guides/drop-label.png
  documentation/guides/drop.md
  documentation/guides/kick.md
  documentation/guides/reverb-photo.png
  documentation/guides/reverb-ram-perf.png
  documentation/guides/reverb-sdram-check.png
  documentation/guides/reverb.md
  documentation/img/logo.svg
  documentation/index.md
  documentation/make.bat
  requirements/documentation.txt
  samples/bypass/README.md
  samples/drop/README.md
  samples/kick/README.md
  samples/reverb/README.md
Labels: documentation

#277 Fix repository readme small typos
  README.md
Labels: enhancement
