Repository ohmtech-rdi/eurorack-blocks, pull requests merged in 2023-06, with the labels that each got.

#527 Update erb toolchain to v0.2
  build-system/setup/__init__.py
Labels: bug

#529 Sram alloc linker
  include/erb/config.h
  src/detail/Sdram.cpp
  src/detail/Sram.cpp
Labels: enhancement

#530 Semihosting support
  build-system/erbb/__init__.py
  build-system/erbb/generators/daisy/Makefile_template
  build-system/erbb/generators/vscode/launch_template.json
  build-system/erbb/generators/vscode/tasks_template.json
  build-system/erbui/generators/daisy/code_template.cpp
  build-system/scripts/erbb
Labels: feature

#532 Fix firmware release launch executable
  build-system/erbb/generators/vscode/launch.py
  build-system/erbb/generators/vscode/launch_template.json
Labels: bug

#531 Add stlink auto detection
  README.md
  build-system/erbb/__init__.py
  build-system/scripts/erbb
  documentation/max/setup.md
  requirements/build-system.txt
Labels: bug, enhancement

#541 Max jack detection
  build-system/erbui/generators/max/code.py
  documentation/max/ui.md
  test/max_npr/Max.erbb
  test/max_npr/Max.erbui
  test/max_npr/Max.maxpat
Labels: feature

#543 Route drop sample
  samples/drop/Drop.erbui
  samples/drop/artifacts/hardware/Drop.kicad_pcb
  samples/drop/artifacts/hardware/fp-lib-table
Labels: enhancement

#546 Error on space in path
  build-system/erbb/__init__.py
  build-system/scripts/erbb
  build-system/setup/__init__.py
Labels: bug

#545 Refine license and add all toolchain licenses
  LICENSE
  README.md
Labels: enhancement

#549 Cache kicad pcb and sch parser output
  build-system/erbui/generators/kicad/pcb.py
  build-system/erbui/generators/kicad/sch.py
Labels: enhancement

#551 Force cache precomputation for all front pcb parts during erbb setup
  build-system/erbui/generators/kicad/pcb.py
  build-system/erbui/generators/kicad/sch.py
  build-system/scripts/erbb
  build-system/setup/__init__.py
Labels: enhancement

#557 Erbb refactor args
  .github/workflows/macos_11.yml
  .github/workflows/ubuntu_20_04.yml
  .github/workflows/ubuntu_22_04.yml
  .github/workflows/windows_2019.yml
  build-system/build-system.gyp
  build-system/completion/__init__.py
  build-system/completion/arpeggio/__init__.py
  build-system/completion/tests/__init__.py
  build-system/completion/tests/test_completion.py
  build-system/erbb/__init__.py
  build-system/init.fish
  build-system/scripts/erbb
  build-system/scripts/erbb_complete.py
  documentation/diy/routing.md
  documentation/faust/first.md
  documentation/faust/mapping.md
  documentation/getting-started/first.md
  documentation/guides/kick.md
  documentation/max/first.md
Labels: enhancement

#559 Expose the build-system folder in fish shell
  build-system/init.fish
Labels: bug

#564 Fix erbb vscode template
  build-system/erbb/generators/vscode/launch.py
  build-system/erbb/generators/vscode/launch_template.json
  build-system/erbb/generators/vscode/tasks_template.json
  documentation/getting-started/setup-vscode-bash1.png
  documentation/getting-started/setup-vscode-bash2.png
  documentation/getting-started/setup.md
Labels: bug, enhancement

#568 Fix max path use user shell
  max/Eurorack-blocks/javascript/erb.build.js
Labels: bug

#570 Simulator memory pool per instance
  build-system/erbb/generators/simulator/Makefile_template
  build-system/erbui/generators/vcvrack/code_template.cpp
  include/erb/SdramPtr.hpp
  include/erb/SramPtr.hpp
  include/erb/detail/Sdram.h
  include/erb/detail/Sram.h
  include/erb/erb-vcvrack.gypi
  include/erb/vcvrack/ModuleBoard.h
  src/detail/Sdram.cpp
  src/detail/Sram.cpp
  src/vcvrack/ModuleBoard.cpp
  test/unit/test.gyp
Labels: enhancement

#573 Always enable ram mem pool size simulator check
  include/erb/config.h
  include/erb/detail/MonotonicMemoryPool.hpp
  include/erb/detail/fnc.hpp
Labels: enhancement

#574 Add cortext-debug vscode extensions recommendation
  build-system/erbb/generators/vscode/extensions_template.json
Labels: enhancement

#575 Enhance xcode debug experience
  build-system/build-system.gyp
  build-system/erbb/__init__.py
  build-system/erbb/generators/simulator/xcode.py
  build-system/erbb/generators/simulator/xcscheme_template
Labels: enhancement

#576 Erbb setup with xcode support
  build-system/completion/__init__.py
  build-system/scripts/erbb
  build-system/setup/__init__.py
  build-system/setup/xcode/Erbb.ideplugin/Contents/Info.plist
  build-system/setup/xcode/Erbb.ideplugin/Contents/Resources/Erbb.xcplugindata
  build-system/setup/xcode/Erbb.xclangspec
  build-system/setup/xcode/Erbui.ideplugin/Contents/Info.plist
  build-system/setup/xcode/Erbui.ideplugin/Contents/Resources/Erbui.xcplugindata
  build-system/setup/xcode/Erbui.xclangspec
  build-system/setup/xcode/Xcode.SourceCodeLanguage.Erbb.plist
  build-system/setup/xcode/Xcode.SourceCodeLanguage.Erbui.plist
  build-system/xcode/Erbb.ideplugin/Contents/Info.plist
  build-system/xcode/Erbui.ideplugin/Contents/Info.plist
  build-system/xcode/README.md
  build-system/xcode/install.py
Labels: enhancement, feature

#577 Update github actions workflows
  .github/workflows/macos_11.yml
Labels: enhancement

#580 Setup: use ssl certificate for download
  build-system/setup/__init__.py
  build-system/setup/certs.pem
Labels: flaw

#581 Vscode language extension
  build-system/completion/__init__.py
  build-system/scripts/erbb
  build-system/setup/__init__.py
  build-system/setup/vscode/.vscodeignore
  build-system/setup/vscode/README.md
  build-system/setup/vscode/images/erbb_file_screenshot.png
  build-system/setup/vscode/images/erbui_file_screenshot.png
  build-system/setup/vscode/language-configuration.json
  build-system/setup/vscode/package.json
  build-system/setup/vscode/syntaxes/erbb.tmLanguage.json
  build-system/setup/vscode/syntaxes/erbui.tmLanguage.json
Labels: enhancement

#583 Add erbb setup with apt support
  .github/workflows/ubuntu_20_04.yml
  .github/workflows/ubuntu_22_04.yml
  build-system/completion/__init__.py
  build-system/scripts/erbb
Labels: enhancement

#579 erbb setup: install Max package
  build-system/completion/__init__.py
  build-system/scripts/erbb
  build-system/setup/__init__.py
Labels: enhancement

#584 Uniformize gyp settings with build system make files
  eurorack-blocks.gypi
  include/erb/xcode.gypi
Labels: enhancement

#585 Fix setup big sur version
  build-system/setup/__init__.py
Labels: bug

#586 Fix erbb setup download typo
  build-system/setup/__init__.py
Labels: bug
