Repository ohmtech-rdi/eurorack-blocks, pull requests merged in 2023-07, with the labels that each got.

#588 Fix audio in subscript prototype
  include/erb/AudioIn.h
  include/erb/AudioIn.hpp
Labels: bug

#589 Erb audio in tuple size
  include/erb/AudioIn.h
Labels: enhancement

#590 Increase wait time before updating clock and reading GPIO to 400 ticks
  boards/kivu12/firmware/BoardKivu12.hpp
Labels: bug

#593 Change frohmage to frohmager
  documentation/setup/linux-cpp-cli.md
  documentation/setup/linux-cpp-vscode.md
  documentation/setup/macos-cpp-cli.md
  documentation/setup/macos-cpp-vscode.md
  documentation/setup/macos-cpp-xcode.md
  documentation/setup/macos-max.md
  documentation/setup/windows-cpp-cli.md
  documentation/setup/windows-cpp-vscode.md
  documentation/setup/windows-max.md
  documentation/starter-kit/content.md
  documentation/starter-kit/demos-frohmager-assembled.jpg
  documentation/starter-kit/demos-frohmager-parts.jpg
  documentation/starter-kit/demos-frohmager-pins.jpg
  documentation/starter-kit/demos-frohmager-screw.jpg
  documentation/starter-kit/demos.md
Labels: documentation

#540 Add support for simulator plugin install
  build-system/completion/__init__.py
  build-system/erbb/__init__.py
  build-system/scripts/erbb
Labels: feature

#594 Fix erbb simulator
  build-system/erbb/__init__.py
Labels: bug

#592 Sample frohmager
  .github/workflows/macos_11.yml
  .github/workflows/ubuntu_20_04.yml
  .github/workflows/ubuntu_22_04.yml
  .github/workflows/windows_2019.yml
  README.md
  samples/frohmager/Frohmager.erbb
  samples/frohmager/README.md
  samples/frohmager/artifacts/daisy/Release/Frohmager.bin
  samples/frohmager/artifacts/daisy/Release/Frohmager.elf
  samples/frohmager/artifacts/simulator/Release/package/plugin.dll
  samples/frohmager/artifacts/simulator/Release/package/plugin.dylib
  samples/frohmager/artifacts/simulator/Release/package/plugin.json
  samples/frohmager/artifacts/simulator/Release/package/plugin.so
  samples/frohmager/artifacts/simulator/Release/package/res/dailywell.2ms.1.svg
  samples/frohmager/artifacts/simulator/Release/package/res/dailywell.2ms.2.svg
  samples/frohmager/artifacts/simulator/Release/package/res/dailywell.2ms.3.svg
  samples/frohmager/artifacts/simulator/Release/package/res/panel_vcvrack.svg
  samples/frohmager/artifacts/simulator/Release/package/res/rogan.1ps.svg
  samples/frohmager/artifacts/simulator/Release/package/res/rogan.1s.black.svg
  samples/frohmager/artifacts/simulator/Release/package/res/rogan.1s.svg
  samples/frohmager/artifacts/simulator/Release/package/res/rogan.2ps.svg
  samples/frohmager/artifacts/simulator/Release/package/res/rogan.2s.black.svg
  samples/frohmager/artifacts/simulator/Release/package/res/rogan.3ps.svg
  samples/frohmager/artifacts/simulator/Release/package/res/rogan.5ps.svg
  samples/frohmager/artifacts/simulator/Release/package/res/rogan.6ps.svg
  samples/frohmager/artifacts/simulator/Release/package/res/sifam.dbn151.white.svg
  samples/frohmager/artifacts/simulator/Release/package/res/sifam.drn111.white.svg
  samples/frohmager/artifacts/simulator/Release/package/res/songhuei.9mm.svg
  samples/frohmager/artifacts/simulator/Release/package/res/thonk.pj398sm.hex.svg
  samples/frohmager/artifacts/simulator/Release/package/res/thonk.pj398sm.knurled.svg
  samples/frohmager/screenshot.png
Labels: feature

#595 Update documentation
  documentation/diy/intro.md
  documentation/documentation.gyp
  documentation/index.md
  documentation/starter-kit/box.png
  documentation/starter-kit/content.md
  documentation/starter-kit/demos.md
  documentation/starter-kit/intro-box-inside.jpg
  documentation/starter-kit/intro-requirements.jpg
  documentation/starter-kit/intro.md
  documentation/starter-kit/kivu12-parts.jpg
  documentation/starter-kit/kivu12.md
  documentation/starter-kit/requirements-hakko-soldering-iron.png
  documentation/starter-kit/requirements-hakko-soldering-tip.png
  documentation/starter-kit/requirements-plato-shear-cutter.png
  documentation/starter-kit/requirements-weller-solder.png
  documentation/starter-kit/requirements.md
Labels: documentation, enhancement

#596 Update samples photo
  README.md
  samples/drop/photo.png
  samples/frohmager/README.md
  samples/frohmager/photo-bg.jpg
  samples/frohmager/photo.png
Labels: documentation, enhancement

#598 Fix deadlink for getting started
  README.md
Labels: documentation

#600 Fix erbui offset
  build-system/erbui/generators/detail/panel.py
  build-system/erbui/grammar.py
  build-system/erbui/visitor.py
Labels: bug

#602 Fix stack size check
  build-system/erbui/generators/daisy/code_template.cpp
  build-system/erbui/generators/vcvrack/code_template.cpp
Labels: enhancement

#603 Relocate daisy main inside the firmware target folder
  build-system/erbb/generators/daisy/make.py
  build-system/erbui/generators/daisy/code.py
  build-system/erbui/generators/daisy/code_template.cpp
Labels: enhancement

#604 Erbb performance target
  boards/kivu12/firmware/BoardKivu12.h
  build-system/build-system.gyp
  build-system/completion/__init__.py
  build-system/completion/tests/test_completion.py
  build-system/erbb/__init__.py
  build-system/erbb/generators/action/action.py
  build-system/erbb/generators/action/action_perf_template.py
  build-system/erbb/generators/perf/Makefile_template
  build-system/erbb/generators/perf/__init__.py
  build-system/erbb/generators/perf/make.py
  build-system/erbui/__init__.py
  build-system/erbui/generators/perf/code.py
  build-system/erbui/generators/perf/code_template.cpp
  build-system/scripts/erbb
  build-system/setup/__init__.py
  include/erb/config.h
  include/erb/daisy/SubmoduleDaisyPatchSm.h
  include/erb/daisy/SubmoduleDaisyPatchSm.hpp
  include/erb/daisy/SubmoduleDaisySeed.h
  include/erb/daisy/SubmoduleDaisySeed.hpp
Labels: feature

#605 Fix kivu12 number of pca9685 led drivers
  boards/kivu12/firmware/BoardKivu12.h
  boards/kivu12/firmware/BoardKivu12.hpp
Labels: bug

#606 Kivu12 led driver bg thread
  boards/daisy_field/firmware/BoardDaisyField.h
  boards/daisy_micropatch/firmware/BoardDaisyMicropatch.h
  boards/kivu12/firmware/BoardKivu12.h
  boards/kivu12/firmware/BoardKivu12.hpp
  build-system/erbui/generators/daisy/code_template.cpp
  build-system/erbui/generators/perf/code_template.cpp
  samples/custom/board/BoardFirmware.h
  src/daisy/SubmoduleDaisyPatchSm.cpp
  src/daisy/SubmoduleDaisySeed.cpp
Labels: bug

#607 Use bss section for sramptr
  src/detail/Sram.cpp
Labels: bug

#609 Add support for semihosting in performance target
  build-system/completion/__init__.py
  build-system/erbb/__init__.py
  build-system/erbui/generators/perf/code_template.cpp
  build-system/scripts/erbb
Labels: feature

#611 Move section sram sramptr to ram d2 instead of stack section
  build-system/erbb/generators/daisy/make.py
  build-system/erbb/generators/linker/STM32H750IB_sram_ramd2.lds
  build-system/erbb/generators/perf/make.py
Labels: enhancement

#612 Fix erbui switch
  include/erb/Switch.hpp
  include/erb/vcvrack/resource/dailywell.2ms.1.svg
  include/erb/vcvrack/resource/dailywell.2ms.3.svg
  samples/drop/Drop.cpp
Labels: bug
